# Generated by Django 5.2.7 on 2025-11-07 14:52

import authapp.fields.byte_stream
import django.db.models.deletion
import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('subscription', django_mysql.models.EnumField(choices=[('own', 'Own'), ('google', 'Google'), ('github', 'Github')], default='own')),
                ('confirmed_registration', models.BooleanField(default=False)),
                ('account_active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_id_hash', authapp.fields.byte_stream.ByteStreamField(stream_size=60)),
                ('user_idx', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='GithubID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id_hash', authapp.fields.byte_stream.ByteStreamField(stream_size=60)),
                ('user_idx', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserRefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refresh_token_hash', authapp.fields.byte_stream.ByteStreamField(stream_size=64, unique=True)),
                ('expiration', models.DateTimeField(auto_now=True)),
                ('user_idx', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authapp.user')),
            ],
        ),
    ]
