"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import sys

import pymysql
import configparser
from Shared.deltatime import string_to_timedelta
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import ec

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

config = configparser.ConfigParser()
config.read(BASE_DIR / "env_vars.ini")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-zb3g++t=d$e&upq3bhc$h+3e+^67ecmr8jnlcdsk@yobcbwz$x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

HMAC_BASE_KEY : str = config.get('HMAC', 'base_key')

MYSQL_DB_NAME : str = config.get('MYSQL', 'db_name')
MYSQL_DB_USER : str = config.get('MYSQL', 'db_user')
MYSQL_DB_PASSWORD : str = config.get('MYSQL', 'db_password')

GOOGLE_CLIENT_ID = config.get('GOOGLE_AUTH', 'id')
GOOGLE_CLIENT_SECRET = config.get('GOOGLE_AUTH', 'secret')
GOOGLE_REDIRECT_URI_LOGIN = config.get('GOOGLE_AUTH', 'redirect_url_login')
GOOGLE_AUTH_URL = 'https://accounts.google.com/o/oauth2/auth'
GOOGLE_TOKEN_URL = 'https://oauth2.googleapis.com/token'

GITHUB_CLIENT_ID = config.get('GITHUB_AUTH', 'id')
GITHUB_CLIENT_SECRET = config.get('GITHUB_AUTH', 'secret')
GITHUB_REDIRECT_URI_LOGIN = config.get('GITHUB_AUTH', 'redirect_url_login')

JWT_KEY_DIR : str = config.get('JWT', 'keys_dir')

ACCESS_TOKEN_LIFETIME = string_to_timedelta(config.get('TOKEN_LIFETIME', 'access'))
REFRESH_TOKEN_LIFETIME = string_to_timedelta(config.get('TOKEN_LIFETIME', 'refresh'))
ACTION_TOKEN_LIFETIME = string_to_timedelta(config.get('TOKEN_LIFETIME', 'action'))

REDIS_HOST = config.get('REDIS', 'full_host')

JWT_PUB_KEY_FILE = JWT_KEY_DIR + 'public_key.pem'
JWT_PRIV_KEY_FILE = JWT_KEY_DIR + 'private_key.pem'

ACCESS_TOKEN_CACHE_TIMEOUT = int(config.get('CACHE_TOKEN_TIMEOUT', 'access'))
REFRESH_TOKEN_CACHE_TIMEOUT = int(config.get('CACHE_TOKEN_TIMEOUT', 'refresh'))

FRONTEND_ROUTER_BASE_ROUTE = config.get('FRONTEND_ROUTER', 'base_route')
FRONTEND_ROUTER_TOKEN_REDIRECT = config.get('FRONTEND_ROUTER', 'token_redirect')

try:
    with open(JWT_PRIV_KEY_FILE, "rb") as key_file:
        JWT_PRIVATE_KEY  = serialization.load_pem_private_key(
            key_file.read(),
            password=None
        )
except FileNotFoundError:
    # Generate EC private key using secp521r1 curve
    JWT_PRIVATE_KEY = ec.generate_private_key(ec.SECP521R1())

    # Save private key to a file in PEM format
    with open("private_key.pem", "wb") as private_key_file:
        private_key_file.write(
            JWT_PRIVATE_KEY.private_bytes(
                encoding=serialization.Encoding.PEM,
                format=serialization.PrivateFormat.TraditionalOpenSSL,  # Traditional PEM format
                encryption_algorithm=serialization.NoEncryption()  # No password protection
            )
        )

JWT_PUBLIC_KEY = JWT_PRIVATE_KEY.public_key()

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'authapp'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

pymysql.install_as_MySQLdb()

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': MYSQL_DB_NAME,
        'USER': MYSQL_DB_USER,
        'PASSWORD': MYSQL_DB_PASSWORD,
        'HOST': 'localhost',
        'PORT': 3306
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
